title: Daisy Seed and Plug Data
baseurl: "/DIY-Synth-DaisySeed-and-PlugData"
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

just_the_docs:
  color_scheme: "dark"
  dark_mode:
    enabled: true

navigation:
  structure: _data/navigation.yml
